#!/usr/bin/env bash

RUBY="ruby"

function r() {
	echo "$@"
	"$@"
}

function preprocess() {
	file="$1"
	out="$(dirname "$file")/$(basename "$file" mpl)"
	r "$RUBY" mplex -rmpl "$file" -o "$out"
	if [ "$?" != 0 ]; then
		echo ""
		echo "** preprocess failed **"
		echo ""
		exit 1
	fi
}

if [ "$1" == "clean" ];then
	rm -f src/msgpack/rpc/caller.h
	rm -f src/cclog/cclog.h
else
	preprocess src/msgpack/rpc/caller.hmpl
	preprocess src/cclog/cclog.hmpl
fi

